### ISSUE TITLE
num2words() got an unexpected keyword argument 'split'

### ISSUE THREAD

**Issue by coding-dallas** [AI4Bharat/indic-numtowords#5]
I am getting the below issue

Traceback (most recent call last):
  File "/home/kesav/Desktop/testing/normalize.py", line 3, in <module>
    words = num2words(156, lang='ml', split=True)
TypeError: num2words() got an unexpected keyword argument 'split'

**Comment by mehak1309** [comment]
The split argument is an experimental feature. Please download the repo and install from source to use it.

**Comment by mehak1309** [comment]
> I am getting the below issue
> 
> Traceback (most recent call last): File "/home/kesav/Desktop/testing/normalize.py", line 3, in words = num2words(156, lang='ml', split=True) TypeError: num2words() got an unexpected keyword argument 'split'


The split argument is an experimental feature. Please download the repo and install from source to use it.
